package persistence;

import entities.Album;
import java.util.List;
/**
 * Data Access Object interface for Album entity
 * Defines all database operations for the Album table
 *
 * This interface follows the DAO pattern to separate business logic
 * from database access logic. All methods throw Exception to handle
 * any database-related errors that may occur.
 *
 * @author Jeremiah
 */

public interface AlbumDao {

    /**
     * Retrieves all albums from the database
     * CA Requirement: Supports "Viewing all albums for an artist"
     *
     * @return List of all Album objects, ordered by release year (descending) and title
     * @throws Exception if a database error occurs during retrieval
     */

    List<Album> getAllAlbums() throws Exception;

    /**
     * Retrieves a specific album by its unique ID
     *
     * @param albumId the ID of the album to retrieve
     * @return Album object if found, null otherwise
     * @throws Exception if a database error occurs during retrieval
     */
    Album getAlbumById(int albumId) throws Exception;

    /**
     * Retrieves all albums for a specific artist
     * CA Requirement: "Viewing all albums for an artist"
     *
     * @param artistId the ID of the artist whose albums to retrieve
     * @return List of Album objects for the specified artist, ordered by release year (descending)
     * @throws Exception if a database error occurs during retrieval
     */
    List<Album> getAlbumsByArtistId(int artistId) throws Exception;

    /**
     * Searches for albums by title using partial, case-insensitive matching
     * CA Requirement: Part of "Searching for songs by title/artist/album/genre"
     *
     * @param title the album title to search for (partial match supported)
     * @return List of Album objects matching the search criteria, ordered alphabetically
     * @throws Exception if a database error occurs during search
     */
    List<Album> searchAlbumsByTitle(String title) throws Exception;

    /**
     * Inserts a new album into the database
     * The album_id will be auto-generated by the database
     *
     * @param album the Album object to insert (albumId will be ignored and auto-generated)
     * @return the Album object with the generated albumId populated
     * @throws Exception if a database error occurs during insertion
     */
    Album insertAlbum(Album album) throws Exception;

    /**
     * Updates an existing album in the database
     * All fields of the album will be updated based on the albumId
     *
     * @param album the Album object with updated data (must have valid albumId)
     * @return true if the update was successful (1 row affected), false otherwise
     * @throws Exception if a database error occurs during update
     */
    boolean updateAlbum(Album album) throws Exception;

    /**
     * Deletes an album from the database
     * Note: This will CASCADE DELETE all songs on this album due to foreign key constraints
     *
     * @param albumId the ID of the album to delete
     * @return true if the deletion was successful (1 row affected), false otherwise
     * @throws Exception if a database error occurs during deletion
     */
    boolean deleteAlbum(int albumId) throws Exception;

}

