package persistence;

import entities.Song;
import java.util.List;

/**
 * Data Access Object interface for Song entity
 * Defines all database operations for the Song table
 *
 * This interface follows the DAO pattern to separate business logic
 * from database access logic. All methods throw Exception to handle
 * any database-related errors that may occur.
 *
 * @author Jeremiah
 */

public interface SongDao {

    /**
     * Retrieves all songs from the database
     *
     * @return List of all Song objects, ordered alphabetically by song title
     * @throws Exception if a database error occurs during retrieval
     */
    List<Song> getAllSongs() throws Exception;

    /**
     * Retrieves a specific song by its unique ID
     *
     * @param songId the ID of the song to retrieve
     * @return Song object if found, null otherwise
     * @throws Exception if a database error occurs during retrieval
     */
    Song getSongById(int songId) throws Exception;

    /**
     * Retrieves all songs on a specific album
     * Songs are returned in track order for proper album playback sequence
     *
     * @param albumId the ID of the album whose songs to retrieve
     * @return List of Song objects for the specified album, ordered by track number
     * @throws Exception if a database error occurs during retrieval
     */
    List<Song> getSongsByAlbumId(int albumId) throws Exception;

    /**
     * Retrieves all songs by a specific artist
     * CA Requirement: Part of "Searching for songs by artist"
     *
     * @param artistId the ID of the artist whose songs to retrieve
     * @return List of Song objects for the specified artist, ordered by release year and title
     * @throws Exception if a database error occurs during retrieval
     */
    List<Song> getSongsByArtistId(int artistId) throws Exception;

    /**
     * Searches for songs by title using partial, case-insensitive matching
     * CA Requirement: "Searching for songs by title"
     *
     * @param title the song title to search for (partial match supported)
     * @return List of Song objects matching the search criteria, ordered alphabetically
     * @throws Exception if a database error occurs during search
     */
    List<Song> searchSongsByTitle(String title) throws Exception;

    /**
     * Retrieves all songs for a specific genre
     * CA Requirement: "Searching for songs by genre"
     *
     * This method requires a JOIN with the SongGenre junction table
     * to support the many-to-many relationship between Song and Genre
     *
     * @param genreId the ID of the genre whose songs to retrieve
     * @return List of Song objects for the specified genre, ordered alphabetically
     * @throws Exception if a database error occurs during retrieval
     */
    List<Song> getSongsByGenreId(int genreId) throws Exception;

    /**
     * Inserts a new song into the database
     * The song_id will be auto-generated by the database
     *
     * @param song the Song object to insert (songId will be ignored and auto-generated)
     * @return the Song object with the generated songId populated
     * @throws Exception if a database error occurs during insertion
     */
    Song insertSong(Song song) throws Exception;

    /**
     * Updates an existing song in the database
     * All fields of the song will be updated based on the songId
     *
     * @param song the Song object with updated data (must have valid songId)
     * @return true if the update was successful (1 row affected), false otherwise
     * @throws Exception if a database error occurs during update
     */
    boolean updateSong(Song song) throws Exception;

    /**
     * Deletes a song from the database
     * Note: This will CASCADE DELETE all ratings for this song due to foreign key constraints
     *
     * @param songId the ID of the song to delete
     * @return true if the deletion was successful (1 row affected), false otherwise
     * @throws Exception if a database error occurs during deletion
     */
    boolean deleteSong(int songId) throws Exception;

}
