package entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for Album entity
 * Represents an album in the music library system
 * Maps to the Album table in the database
 *
 * Database Schema Mapping:
 * - album_id (INT, PRIMARY KEY, AUTO_INCREMENT)
 * - artist_id (INT, FOREIGN KEY -> Artist.artist_id)
 * - album_title (VARCHAR(150))
 * - release_year (INT)
 * - album_art_url (VARCHAR(255))
 * - total_tracks (INT)
 *
 * @author Jeremiah
 */


@Data                    // Lombok: Generates getters, setters, toString, equals, hashCode
@NoArgsConstructor       // Lombok: Generates no-argument constructor
@AllArgsConstructor      // Lombok: Generates constructor with all fields


public class Album {

    private int albumId;
    private int artistId;
    private String albumTitle;
    private int releaseYear;
    private String albumArtUrl;
    private int totalTracks;

    /**
     * Constructor without album ID (for inserting new albums)
     * The album ID will be auto-generated by the database
     * Use this constructor when creating a new album to insert into the database
     *
     * @param artistId the ID of the artist who released this album
     * @param albumTitle the title of the album
     * @param releaseYear the year the album was released (e.g., 1969)
     * @param albumArtUrl URL to the album artwork (can be null)
     * @param totalTracks total number of tracks on the album
     */
    public Album(int artistId, String albumTitle, int releaseYear, String albumArtUrl, int totalTracks) {
        this.artistId = artistId;
        this.albumTitle = albumTitle;
        this.releaseYear = releaseYear;
        this.albumArtUrl = albumArtUrl;
        this.totalTracks = totalTracks;
    }
    /**
     * Constructor with minimal required fields (for quick object creation)
     * Sets albumArtUrl to null and totalTracks to 0
     *
     * @param artistId the ID of the artist who released this album
     * @param albumTitle the title of the album
     * @param releaseYear the year the album was released
     */
    public Album(int artistId, String albumTitle, int releaseYear) {
        this.artistId = artistId;
        this.albumTitle = albumTitle;
        this.releaseYear = releaseYear;
        this.albumArtUrl = null;
        this.totalTracks = 0;
    }
}

