package entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for Song entity
 * Represents a song/track in the music library system
 * Maps to the Song table in the database
 *
 * Database Schema Mapping:
 * - song_id (INT, PRIMARY KEY, AUTO_INCREMENT)
 * - album_id (INT, FOREIGN KEY -> Album.album_id)
 * - artist_id (INT, FOREIGN KEY -> Artist.artist_id)
 * - song_title (VARCHAR(150))
 * - duration_seconds (INT) - stores duration in seconds
 * - track_number (INT)
 * - release_year (INT)
 *
 * Note: Rating information (average rating, rating count) should NOT be stored here.
 * It should be calculated from the Rating table when needed.
 *
 * @author Jeremiah
 */

@Data
@AllArgsConstructor
@NoArgsConstructor

public class Song {

    private int songId;
    private int albumId;
    private int artistId;
    private String songTitle;
    private int durationSeconds;
    private int trackNumber;
    private int releaseYear;

    /**
     * Constructor without song ID (for inserting new songs)
     * The song ID will be auto-generated by the database
     * Use this constructor when creating a new song to insert into the database
     *
     * @param albumId the ID of the album this song belongs to
     * @param artistId the ID of the artist who performed this song
     * @param songTitle the title of the song
     * @param durationSeconds the duration of the song in seconds (e.g., 225 for 3:45)
     * @param trackNumber the track number on the album
     * @param releaseYear the year the song was released
     */

    public Song(int albumId, int artistId, String songTitle, int durationSeconds, int trackNumber, int releaseYear) {
        this.albumId = albumId;
        this.artistId = artistId;
        this.songTitle = songTitle;
        this.durationSeconds = durationSeconds;
        this.trackNumber = trackNumber;
        this.releaseYear = releaseYear;

    }

    /**
     * Constructor with minimal required fields (for quick object creation)
     * Sets trackNumber to 0 and releaseYear to current year
     *
     * @param albumId the ID of the album this song belongs to
     * @param artistId the ID of the artist who performed this song
     * @param songTitle the title of the song
     * @param durationSeconds the duration of the song in seconds
     */

    public Song(int albumId, int artistId, String songTitle, int durationSeconds) {
        this.albumId = albumId;
        this.artistId = artistId;
        this.songTitle = songTitle;
        this.durationSeconds = durationSeconds;
        this.trackNumber = 0;
        this.releaseYear = java.time.Year.now().getValue();  // current year

    }

    /**
     * Convenience method to format duration for display
     * Converts durationSeconds to MM:SS format
     *
     * Examples:
     * - 225 seconds -> "3:45"
     * - 65 seconds -> "1:05"
     * - 3661 seconds -> "61:01"
     *
     * @return formatted duration string in MM:SS format
     */

    public String getDurationFormatted() {
        int minutes = durationSeconds / 60;
        int seconds = durationSeconds % 60;
        return String.format("%02d:%02d", minutes, seconds);
    }

    /**
     * Convenience method to set duration from MM:SS format string
     * Parses a string like "3:45" and sets durationSeconds to 225
     *
     * @param formattedTime string in MM:SS format (e.g., "3:45")
     * @throws IllegalArgumentException if format is invalid
     */

    public void setDurationFromFormatted(String formattedTime) {
        if (formattedTime == null || !formattedTime.contains(":")) {
            throw new IllegalArgumentException("Time must be in MM:SS format");
        }

        String[] parts = formattedTime.split(":");
        if (parts.length != 2) {
            throw new IllegalArgumentException("Time must be in MM:SS format");
        }

        try {
            int minutes = Integer.parseInt(parts[0]);
            int seconds = Integer.parseInt(parts[1]);

            if (seconds < 0 || seconds >= 60) {
                throw new IllegalArgumentException("Seconds must be between 0 and 59");
            }

            this.durationSeconds = (minutes * 60) + seconds;
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Invalid time format: " + formattedTime);
        }
    }












}
